# https://jupyterbook.org/customize/config.html

title: Computing in Context (SIPA)
author: Aidan Feldman

# https://jupyterbook.org/en/stable/structure/configure.html#disable-building-files-that-arent-in-the-table-of-contents
only_build_toc_files: true
exclude_patterns:
  - .github/*
  - .pytest_cache/*

repository:
  url: https://github.com/afeld/computing-in-context

execute:
  execute_notebooks: "off"

html:
  # https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
  use_repository_button: true
  extra_footer: |
    <div>
      <a href="https://creativecommons.org/publicdomain/zero/1.0/">
        <img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg" alt="Creative Commons 0 1.0" />
      </a>
    </div>

sphinx:
  config:
    html_show_copyright: false
    # https://jupyterbook.org/advanced/html.html#configuring-to-improve-accessibility
    language: en
    # https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder
    linkcheck_ignore:
      # invalid cert
      - ^https://www.open311.org
      # behind Cloudflare; get 403s
      - ^https://(.+\.)?substack\.com
      - ^https://(.+\.)?columbia\.edu
      - ^https://guides.gradescope.com+
    linkcheck_report_timeouts_as_broken: false
    # https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#implicit-targets
    myst_heading_anchors: 4
    html_extra_path:
      - MessyData.csv
