# https://jupyterbook.org/customize/config.html

title: Computing in Context (SIPA)
author: Aidan Feldman

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

repository:
  url: https://github.com/afeld/computing-in-context

html:
  # https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
  use_repository_button: true
  extra_footer: |
    <div>
      <a href="https://creativecommons.org/publicdomain/zero/1.0/">
        <img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg" alt="Creative Commons 0 1.0" />
      </a>
    </div>

sphinx:
  config:
    html_show_copyright: false
    # https://jupyterbook.org/advanced/html.html#configuring-to-improve-accessibility
    language: en
    # https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#implicit-targets
    myst_heading_anchors: 4
