name: computing-in-context
channels:
  - default
  - conda-forge
dependencies:
  - ipykernel
  - jupyter-book
  - jupyterlab
  - jupyterlab_rise
  - nb_conda_kernels
  - nbdime
  - nbformat
  - pytest
  # https://github.com/sphinx-doc/sphinx/issues/10440#issuecomment-1556180835
  - sphinx>=6.2.0
