name: Linkcheck

on:
  schedule:
    # nightly
    - cron: "0 0 * * *"

jobs:
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  build:
    runs-on: ubuntu-latest
    # https://github.com/mamba-org/provision-with-micromamba#important
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check for broken links
        run: make linkcheck
