name: Run tests

on: push

jobs:
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  pytest:
    runs-on: ubuntu-latest
    # https://github.com/mamba-org/provision-with-micromamba#important
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Run tests
        run: pytest

      - name: Build and check for broken links
        # https://jupyterbook.org/en/stable/advanced/sphinx.html#enable-a-custom-sphinx-builder-from-the-cli
        # https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#test-external-links
        run: jupyter-book build --builder=linkcheck .
